services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - task-db-volume:/app
      - ./logs:/app/logs
    restart: on-failure
    depends_on:
      - task_service
  task_service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - task-db-volume:/app
    restart: on-failure


volumes:
  task-db-volume: