services:
  web:
    build:
      context: ./web_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - task-web-volume:/app
    restart: on-failure
    depends_on:
      - task_service
  task_service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - task-service-volume:/app
    restart: on-failure


volumes:
  task-web-volume:
  task-service-volume: