services:
  web:
    build:
      context: ./web_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - task-web-volume:/app
    restart: on-failure
    depends_on:
      - task_service
      - manual_reader_service
  task_service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - task-service-volume:/app
    restart: on-failure
  manual_reader_service:
    build:
      context: ./manual_reader_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - vectorstore-volume:/app/vectorstores
    restart: on-failure
    environment:
        OPENAI_API_KEY: ${OPENAI_API_KEY}


volumes:
  task-web-volume:
  task-service-volume:
  vectorstore-volume: